version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gatherly_rails
    environment:
      - RAILS_ENV=development
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gatherly_development
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    depends_on:
      - db
    networks:
      - gatherly_network

  # PostgreSQL Database
  db:
    image: postgres:13
    container_name: gatherly_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gatherly_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gatherly_network

volumes:
  postgres_data:
    driver: local

networks:
  gatherly_network:
    driver: bridge