name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: my_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t gatherly-rails .

      - name: Set up Ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1

      - name: Set up Bundler
        run: gem install bundler -v 2.5.14

      - name: Install gems
        run: |
          docker run --rm -v $(pwd):/app -w /app gatherly-rails bundle install

      - name: Prepare Database
        run: |
          docker run --rm -v $(pwd):/app -w /app gatherly-rails bundle exec rake db:create db:migrate

      - name: Run RSpec tests
        run: |
          docker run --rm -v $(pwd):/app -w /app gatherly-rails bundle exec rspec

      - name: Run RuboCop
        run: |
          docker run --rm -v $(pwd):/app -w /app gatherly-rails bundle exec rubocop

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: /bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run RuboCop Linting
        run: |
          gem install rubocop -v 1.27.0
          rubocop --format simple